### PR TITLE
feat: add shell.nix

### PR DESCRIPTION
**Pull request by bitgopatmcl**
This one is very minimal, but it works

### CODE REVIEW

**Comment by bitgopatmcl** [comment]
Node 12 CI fixed in #30

**Review by ericcrosson-bitgo — APPROVED** [review]
What about an `.envrc` file?

**Comment by bitgopatmcl** [comment]
> What about an .envrc file?

That would require us to decide to standardize on using `lorri` or possibly some similar plugin

**Comment by ericcrosson-bitgo** [comment]
I could get behind that

**Comment by EricCrosson** [comment]
Just seen https://github.com/nix-community/nix-direnv

**Pull request merged**
