### PR TITLE
feat: support array examples at arbitrary levels

### PR DESCRIPTION
**Pull request by ad-world**
DX-622

This PR removes support for the @arrayExample jsdoc, and extends the functionality of the @example tag so that it can be used with arrays to show array example and non-array examples as well. 

This is how to use the new functionality.

Case 1. 
Want to show an example of an item within the array
```
/**
@example exampleItem
*/
field: t.array(t.string)
```

This will render as this:
```
{
    type: 'array',
    items: {
        type: 'string',
        example: 'exampleItem'
    }
}
```

Case 2. Want to render an array example
```
/**
@example ["exampleItem1", "exampleItem2"]
*/
field: t.array(t.string)
```

This is how it would render:
```
{
    type: 'array',
    example: ['exampleItem1', 'exampleItem2']
    items: {
        type: 'string'    
    }
}
```

Case 3. Want to render an item + array example

```
/**
@example btc
*/
const coinString = t.string

... 
/** 
@example ["btc", "eth"]
field: t.array(coinString)
*/
```

This is how it would render:
```
{
    type: 'array',
    example: ['btc', 'eth']
    items: {
        type: 'string',
        example: 'btc'
    }
}
```

### CODE REVIEW

**Review by ericcrosson-bitgo — COMMENTED** [review]
Test cases look good.

What is your plan regarding call-sites that are using `arrayExample` today? 

Please add the missing semicolon that the linter flagged and once we have a solid roll-out plan, this looks good to merge

**Comment by ad-world** [comment]
> What is your plan regarding call-sites that are using `arrayExample` today?

First step is to bump openapi-generator in dev-portal (after this is merged).
Next step is to update all @arrayExample's in WPT. There are only 2, so it is a trivial task.

**Comment by ad-world** [comment]
https://github.com/BitGo/wallet-platform-types/pull/478 !

**Review by ericcrosson-bitgo — APPROVED** [review]
Seems fine to not consider this a breaking change since the removed `arrayExample` tag is undocumented and was recently added -- so adoption is expected to be minimal.

Approving but not merging yet so you can coordinate this with your other PRs

**Pull request merged**
